_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: c57ddc52-b198-4009-a377-cb6317ac9159
name: k1dxd_sites
mail: k1dxd1998@gmail.com
slogan: 'K1dxd Offer platform'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
